version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout
  
     - run: |
         echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_USERNAME --password-stdin

     - run: docker build -t saikatharryc/api-base:$CIRCLE_BRANCH .

     - run: docker push saikatharryc/api-base:$CIRCLE_BRANCH